// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClliq8_Vf5daSpxMxpHS2D950FVsrbMyA',
    appId: '1:84428417566:web:26eec331d38ce592711c0f',
    messagingSenderId: '84428417566',
    projectId: 'good-job-1',
    authDomain: 'good-job-1.firebaseapp.com',
    storageBucket: 'good-job-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5kuS0vttOSlXXHUckr3UuR6wgHLMN70g',
    appId: '1:84428417566:android:8313b204c7d91fbe711c0f',
    messagingSenderId: '84428417566',
    projectId: 'good-job-1',
    storageBucket: 'good-job-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNbRfNLkHjfKG8hfrBjeSNps68ZMM5jGs',
    appId: '1:84428417566:ios:2361ce0f67f10cb1711c0f',
    messagingSenderId: '84428417566',
    projectId: 'good-job-1',
    storageBucket: 'good-job-1.firebasestorage.app',
    iosBundleId: 'com.example.goodjobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNbRfNLkHjfKG8hfrBjeSNps68ZMM5jGs',
    appId: '1:84428417566:ios:2361ce0f67f10cb1711c0f',
    messagingSenderId: '84428417566',
    projectId: 'good-job-1',
    storageBucket: 'good-job-1.firebasestorage.app',
    iosBundleId: 'com.example.goodjobApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClliq8_Vf5daSpxMxpHS2D950FVsrbMyA',
    appId: '1:84428417566:web:b783364d05773f8e711c0f',
    messagingSenderId: '84428417566',
    projectId: 'good-job-1',
    authDomain: 'good-job-1.firebaseapp.com',
    storageBucket: 'good-job-1.firebasestorage.app',
  );

}